### ISSUE TITLE
Package error when running `yarn run dev` command

### ISSUE THREAD

**Issue by Paiman-Rasoli** [discohook/site#100]
I have cloned the repo, and installed the dependencies using `yarn install` it will successfully install all the packages. but when I want to run the project I face this error.
![image](https://github.com/discohook/site/assets/83835010/8984a885-0ace-4caf-a7a2-2bccd4d4305c)

OS: Windows 10 - 64 bit
Node Version: 18.17.1
Yarn Version: 1.22.19

**Comment by dkay0670** [comment]
Use node 16 instead of 18.

**Comment by Paiman-Rasoli** [comment]
@dkay0670 Many Thanks.
