### ISSUE TITLE
Anytime i try to make a webhook it shows this

### ISSUE THREAD

**Issue by onlysph** [discohook/site#107]
Command 'create' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

WHAT DO I DO?!

**Comment by timontf** [comment]
Kick the bot and re-invite it.
Give it FULL Admin perms and a separate role called "Bot" with those perms.
Try again. If it doesn't work then - idk call me or smth 
Username: timontf

**Comment by shayypy** [comment]
This error occurs when the bot is missing the manage webhooks permission in the target channel.
