### ISSUE TITLE
What is the basic path to bring it online via a VPS?

### ISSUE THREAD

**Issue by GalackQSM** [discohook/site#14]
What is the basic path to bring it online via a VPS?

**Comment by vvvvvvivi** [comment]
Instructions are in the readme, please read them

**Comment by GalackQSM** [comment]
he just has how to start it my steps host him

**Comment by vvvvvvivi** [comment]
Once it's started keep the process in the background, that's your responsibility to figure out

**Comment by GalackQSM** [comment]
yes that I had understood my to host it via a domain name did how finally at least should I put which root of the file?

**Comment by vvvvvvivi** [comment]
That is your job, not mine. I don't know how your server is configured and will not familiarise myself with it, let alone set it up on your behalf.
