### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by CnyAnime** [discohook/site#18]
Dear discohook,
my problem is the font then on my pc it looks really really bad (See picture).
With kind regards,
CnyAnime

![image](https://user-images.githubusercontent.com/56434715/100770759-ea904d00-33fd-11eb-92a6-abeba3fc0099.png)

**Comment by vvvvvvivi** [comment]
Hi, what browser are you using?

**Comment by CnyAnime** [comment]
Google chrome

**Comment by CnyAnime** [comment]
> Hi, what browser are you using?

Google chrome

**Comment by vvvvvvivi** [comment]
Try resetting all settings on `chrome://flags`.

**Comment by CnyAnime** [comment]
> Try resetting all settings on `chrome://flags`.

doesn't work it still the same

**Comment by vvvvvvivi** [comment]
Try disabling "GPU rasterization" there

**Comment by CnyAnime** [comment]
> Try disabling "GPU rasterization" there

it's still the same

**Comment by vvvvvvivi** [comment]
Then I don't know what's wrong and can't help you fix it, either way it's the fault of Google Chrome. Try using another browser for my site.
