### ISSUE TITLE
Footer Dates are Shown Differently In Discohook

### ISSUE THREAD

**Issue by som1chan** [discohook/site#19]
Hi, 

I've been using Discohook a lot now and I've found this tool very useful! I did find a formatting issue with dates though.

### Expected Output (Discohook)

![image](https://user-images.githubusercontent.com/31833556/100806055-69cd5300-33f5-11eb-9934-8ed7e3e0d18c.png)

Here's Discohook's output when I set the date to be 2 days from now. It says Thursday at 12:00 AM.

### Actual Output (Discord)

![image](https://user-images.githubusercontent.com/31833556/100805957-37bbf100-33f5-11eb-9646-963da624687c.png)

Instead of showing Thursday at 12:00 AM, Discord shows 12/03/2020 with no day or time.

Although I wished that the dates were represented as how you programmed it in, Discord is different. From my understanding, I believe you'd like to fix any inconsistencies. Let me know if you need anything else!

**Comment by vvvvvvivi** [comment]
Discohook's output used to be accurate but Discord changed their date formats recently, I'll see if I can reproduce it.

**Comment by vvvvvvivi** [comment]
The site is accurate with Discord again

**Comment by som1chan** [comment]
It used to? Wow, shame that Discord changed it. Thanks for the fix, though!
