### ISSUE TITLE
[Question] Future plans

### ISSUE THREAD

**Issue by BadCoder1337** [discohook/site#20]
Hello, recently I've started a fork to create a CMS-like tool for communities.
I'm trying to build even more native Discord experience with these features:
- post rules & news and edit them subsequently
- link preview
- pickers for emoji, channel, role, etc
- multi-message post

I assume users will use my version as addition to existing collaborative tools such Google Docs.

Your last huge update met my first goal. Do you plan to implement similar features? What's on the roadmap?

**Comment by vvvvvvivi** [comment]
Hey,

After fleshing out issues with the most recent update I think I'll focus on writing an API that would allow logins with Discord. It would replace how backups are stored right now. Maybe backups could be shared between users but live collaborative editing likely won't happen. From there I want to integrate the Discord bot with the site to allow mentions and similar to work semi-automatically.

Multi message posts did get introduced into the most recent update, however they're hidden internally and can only be accessed by manually editing the URL. I'm looking for a way to integrate this nicely in the website design-wise without making simpler use more complicated.

As for link preview, I've had the thought of making my own media proxy which might be able to reproduce Discord's embeds semi reliably, but I don't expect to work on this any time soon.

I hope this answers your question.

**Comment by wolfier74** [comment]
Ok, the guild, channel and emoji picker is good idea. Also role user mentions will be good.
