### ISSUE TITLE
Compact mode text is shifted left in codeblocks

### ISSUE THREAD

**Issue by BannerBomb** [discohook/site#28]
When you have compact view enabled the text in a codeblock in the message content is displayed outside of the codeblock floating to the left.
![image](https://user-images.githubusercontent.com/11788894/104250435-a13f0e80-543b-11eb-9440-93a7505f6cb0.png)

Reproducible code is
````
```
function foo(bar)
```
````

**Comment by BadCoder1337** [comment]
Not broken anymore (Edge, Firefox, Chrome) https://share.discohook.app/go/m87giqey

**Comment by vivisrc** [comment]
The issue specifically mentions compact mode

**Comment by BadCoder1337** [comment]
It's fixed now
