### ISSUE TITLE
Selfhosting question

### ISSUE THREAD

**Issue by ririko5834** [discohook/site#37]
Is this hostable on Netlify or Vercel?

**Comment by vivisrc** [comment]
The site can be deployed with Vercel, no clue about Netlify.

**Comment by ririko5834** [comment]
Thanks, why you dont have deploy to vercel button to readme.md? And what about the bot, where it can be hosted?

**Comment by vivisrc** [comment]
Any VPS service will work. I don't use vercel myself as I'd go over their data allowance caps, and as such can't provide support for it.

**Comment by ririko5834** [comment]
I tried to deploy the site on Vercel:
![image](https://user-images.githubusercontent.com/64729293/113709424-bf3aa900-96e2-11eb-8d34-a2be62b0de53.png)

**Comment by vivisrc** [comment]
The output directory is non-default, change it in Vercel's configuration

**Comment by vivisrc** [comment]
The value should be 'build'
