### ISSUE TITLE
Refreshing a long chain of messages will cause a "Connection Closed" error unless loading from local storage

### ISSUE THREAD

**Issue by kouwei32** [discohook/site#53]
To reproduce:
1. Create a long chain of messages in Discohook that results in the URL expanding to very large lengths (45k characters in my case)
2. Refresh Discohook
3. Observe `ERR_CONNECTION_CLOSED`

This is a serious issue because it can cause unexpected data loss unless a backup is made. Additionally, loading data from URL is generally bad practice too since it can cause massive lag in the browser when address bar autofill is active.

**Comment by vivisrc** [comment]
This error comes from cloudflare's limits and can't be fixed
