### ISSUE TITLE
Share feature: 502 Bad Gateway

### ISSUE THREAD

**Issue by kouwei32** [discohook/site#54]
To reproduce:
1. Create a long chain of messages in Discohook that results in the URL expanding to very large lengths (45k characters in my case) (related to #53)
2. Create a shortlink via the "Share" button
3. Open shortlink
4. Observe `502 Bad Gateway` error from Cloudflare

**Comment by vivisrc** [comment]
This error comes from cloudflare's limits and can't be fixed
