### ISSUE TITLE
Support thread_id query parameter

### ISSUE THREAD

**Issue by 06000208** [discohook/site#59]
Allowing the `?thread_id=` query parameter in urls would enable sending webhooks to threads, ie:

`https://discord.com/api/webhooks/id/token?thread_id=id`

Presently urls which use query parameters are deemed invalid, and it doesn't appear to let you send them

See https://discord.com/developers/docs/topics/threads#webhooks & https://discord.com/developers/docs/resources/webhook#execute-webhook-query-string-params for details

**Comment by shayypy** [comment]
Explicit support (like a "Thread ID" box) would be far better for UX IMO rather than telling users to tack on a query parameter, although I see where you're coming from in that support *in the first place* is better than nothing.

**Comment by 06000208** [comment]
Ah, yeah, it would be better UX. Thought it was implied discohook would likely add an input for thread ids or I would've mentioned it in the op.

**Comment by xMixerek** [comment]
Yep, please add this. That would be useful.
