### ISSUE TITLE
Embed json not working

### ISSUE THREAD

**Issue by XboxBedrock** [discohook/site#67]
This url with a valid base64 json just goes to default, when i manually add the same json in the editor it works, any idea whats going on
https://discohook.org/?data=eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7InRpdGxlIjoiKiojNiA6YWJjZDogRGlzcnVwdGluZyBhbmQgYmFpdGluZyB0aGUgY2hhdCBpcyBub3QgYWxsb3dlZC4qKiIsImRlc2NyaXB0aW9uIjoiLSBUaGlzIGluY2x1ZGVzIHRleHQgc3BhbSwgY29weS1wYXN0ZWQgdGV4dCB3YWxscyBhbmQgc3BvaWxlciBiYWl0aW5nIHRvIG1ha2Ugb3RoZXJzIGJlbGlldmUgaXRzIGEgYmFubmVkIHdvcmQuXG4tIEV4Y2Vzc2l2ZSB1bm5lY2Vzc2FyeSBwaW5ncywgb3ZlcnVzZSBvZiBjYXBzL3RleHQgZm9ybWF0dGluZyBhbmQgdW5uZWNlc3NhcnkgdXNhZ2Ugb2YgdGhlIFN1cHBvcnQgQm90IGFyZSBhbHNvIHRvIGJlIGF2b2lkZWQuIiwiY29sb3IiOjE2Nzc1MTU5fSx7InRpdGxlIjoiKiojNiA6YWJjZDog64Ka7Iuc6riAIOuTseycvOuhnCDrjIDtmZTrpbwg67Cp7ZW07ZWY64qUIO2WieychOuKlCDquIjsp4DrkKnri4jri6QuKioiLCJkZXNjcmlwdGlvbiI6Ii0g7Jes6riw7JeQ64qUIOyKpO2MuCwg67O17IKs7ZWY7JesIOu2meyXrOuEo+ydgCDsnqXrrLgsIOu2iO2VhOyalO2VnCDrqZjshZgsIOq3uOumrOqzoCDsmKTtlbTtlaAg7Jes7KeA6rCAIOyeiOuKlCDsiqTtj6zsnbzrn6zrk6Trj4Qg7Y+s7ZWo65Cp64uI64ukLiIsImNvbG9yIjoxNjcxMTY4MH0seyJ0aXRsZSI6IiM3OmJ1c3RfaW5fc2lsaG91ZXR0ZTogSGF2aW5nIGEgdXNlcm5hbWUvcHJvZmlsZSBwaWN0dXJlL3N0YXR1cy9HYW1lIEFjdGl2aXR5IHRoYXQgY29udGFpbnMgYW55IHZpb2xhdGlvbiBvZiBvdXIgcnVsZXMgaXMgcHJvaGliaXRlZC4iLCJkZXNjcmlwdGlvbiI6Ii0gVGhpcyBhbHNvIGluY2x1ZGVzIGltcGVyc29uYXRpb24gb2YgU3RhZmYgbWVtYmVycyAoSGF2aW5nIGFuIGlkZW50aWNhbCBwcm9maWxlIHBpY3R1cmUgYW5kIHVzZXJuYW1lL25pY2tuYW1lKS4iLCJjb2xvciI6MTY3NzUxNTl9LHsidGl0bGUiOiIjNyA6YnVzdF9pbl9zaWxob3VldHRlOiDsgqzsmqnsnpDrqoXsnbTrgpgg7ZSE66Gc7ZWEIOyCrOynhCwg7IKs7Jqp7J6QIOyngOyglSDsg4Htg5wsIOqyjOyehCDtmZzrj5nsl5Ag7KCA7Z2s7J2YIOq3nOy5meydhCDsnITrsJjtlZjripQg64K07Jqp7J20IOyeiOyWtOyEnOuKlCDslYjrkKnri4jri6QuIiwiZGVzY3JpcHRpb24iOiItIOyXrOq4sOyXkOuKlCDsoIDtnazsnZgg7KeB7JuQ7J2EIOyCrOyaqeyekOuqheydtOuCmCDtlITroZztlYQg7IKs7KeEIOuTseycvOuhnCDsgqzsua3tlZjripQg6rKD64+EIO2PrO2VqOuQqeuLiOuLpC4iLCJjb2xvciI6MTY3MTE2ODB9LHsidGl0bGUiOiIjOCA6dGVsZXBob25lOiBVbnNvbGljaXRlZCBhZHZlcnRpc2luZyAodGhyb3VnaCB2b2ljZSwgdGV4dCBjaGFubmVscywgb3IgRE1zKSBpcyBwcm9oaWJpdGVkLiIsImNvbG9yIjoxNjc3NTE1OX0seyJ0aXRsZSI6IiM4IDp0ZWxlcGhvbmU6ICjsnYzshLEsIO2FjeyKpO2KuCDssYTrhJAsIOqwnOyduCDrqZTshLjsp4Ag65Ox7Jy866GcKSDsoIDtnazqsIAg7LKt7ZWY7KeAIOyViuydgCDrgrTsmqnsnZgg6rSR6rOg65Ok7J2AIOq4iOyngOuQqeuLiOuLpC4iLCJjb2xvciI6MTY3MTE2ODB9LHsidGl0bGUiOiIjOSA6c3BlYWtpbmdfaGVhZDogQWNjdXNpbmcgc29tZW9uZSBmb3IgYnJlYWtpbmcgcnVsZXMgaW4gcHVibGljIGNoYXRzIGlzIHByb2hpYml0ZWQuIiwiZGVzY3JpcHRpb24iOiItIEluc3RhbmNlcyBvZiBzdWNoIGFyZSBjb25zaWRlcmVkIGRlZmFtYXRvcnkuIElmIHlvdSBoYXZlIGFueSBwcm9vZiwgY29udGFjdCBhIFN0YWZmIG1lbWJlciBwcml2YXRlbHkgYWJvdXQgaXQgYW5kIHdlIHdpbGwgaGFuZGxlIHRoZSBzaXR1YXRpb24gYWNjb3JkaW5nbHkuIiwiY29sb3IiOjE2Nzc1MTU5fSx7InRpdGxlIjoiIzkgOnNwZWFraW5nX2hlYWQ6IOuIhOq1sOqwgOqwgCDqt5zsuZnsnYQg7Ja06rK864uk6rOgIOqzteqwnCDssYTtjIXrsKnsl5DshJwg6rOg67Cc7ZWY64qUIO2WieychOuKlCDquIjsp4DrkJjslrTsnojsirXri4jri6QuIiwiZGVzY3JpcHRpb24iOiItIOuqheyYiO2bvOyGkOycvOuhnCDqsITso7zrkJjrr4DroZwsIOunjOyVvSDriITqtbDqsIDqsIAg6rec7LmZ7J2EIOyWtOq4tCDspp3qsbDqsIAg7J6I7Jy87Iuc64uk66m0IOyggO2drCDsp4Hsm5Ag67aE65Ok7KSRIO2VnCDrtoTsl5Dqsowg6rCc7J24IOuplOyEuOyngOuhnCDsi6Dqs6DtlbTso7zshLjsmpQuIiwiY29sb3IiOjE2NzExNjgwfSx7InRpdGxlIjoiIzEwIDpmYWNlX3dpdGhfc3ltYm9sc19vdmVyX21vdXRoOiBHZW5lcmFsIHRveGljIGJlaGF2aW91ciBpcyBub3QgYWxsb3dlZCBpbiBhbnkgY2hhbm5lbHMuIiwiZGVzY3JpcHRpb24iOiItIFRoaXMgaW5jbHVkZXMsIGJ1dCBpcyBub3QgbGltaXRlZCB0bywgZWFycmFwZSwgbG91ZC9hbm5veWluZyBub2lzZXMgYW5kIHNjcmVhbXMgaW4gdm9pY2UgY2hhdHMgYW5kIHBvc3RlZCBhdWRpby92aWRlbyBmaWxlcywgc3ByZWFkaW5nIHNsYW5kZXIvbGllcywgYW5kIHJ1ZGUsIGluc3VsdGluZyBvciBkZXJvZ2F0b3J5IGxhbmd1YWdlIHRvd2FyZHMgdXNlcnMvc3RhZmYuIiwiY29sb3IiOjE2Nzc1MTU5fSx7InRpdGxlIjoiIzEwIDpmYWNlX3dpdGhfc3ltYm9sc19vdmVyX21vdXRoOiDrrLTroYDtlZjqsowg7ZaJ64+Z7ZWY64qUIO2WieychOuKlCDqt7gg7Ja065ag7ZWcIOyxhOuEkOyXkOyEnOuPhCDtl4jsmqnrkJjsp4Ag7JWK7Iq164uI64ukLiIsImRlc2NyaXB0aW9uIjoiLSDsl6zquLDsl5DripQg6rOg66eJIO2FjOufrCwg7Kec7Kad64KY64qUIOyGjOydjCDrsI8g67mE66qFLCDtl4jsnIQg7IKs7IukIOycoO2PrCwg6re466as6rOgIO2DgOyduOydhCDtlqXtlZwg66qo7JqVIOuwjyDsmpXshKTrj4Qg7Y+s7ZWo65Cp64uI64ukLiIsImNvbG9yIjoxNjcxMTY4MH1dLCJ1c2VybmFtZSI6IkNhcHRhaW4gSG9vayIsImF2YXRhcl91cmwiOiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9lbWJlZC9hdmF0YXJzLzAucG5nIn19XX0=

the json
```
{
    "messages": [
        {
            "data": {
                "content": "lol",
                "embeds": [
                    {
                        "title": "**#6 :abcd: Disrupting and baiting the chat is not allowed.**",
                        "description": "- This includes text spam, copy-pasted text walls and spoiler baiting to make others believe its a banned word.\n- Excessive unnecessary pings, overuse of caps/text formatting and unnecessary usage of the Support Bot are also to be avoided.",
                        "color": 16775159
                    },
                    {
                        "title": "**#6 :abcd: 낚시글 등으로 대화를 방해하는 행위는 금지됩니다.**",
                        "description": "- 여기에는 스팸, 복사하여 붙여넣은 장문, 불필요한 멘션, 그리고 오해할 여지가 있는 스포일러들도 포함됩니다.",
                        "color": 16711680
                    },
                    {
                        "title": "#7:bust_in_silhouette: Having a username/profile picture/status/Game Activity that contains any violation of our rules is prohibited.",
                        "description": "- This also includes impersonation of Staff members (Having an identical profile picture and username/nickname).",
                        "color": 16775159
                    },
                    {
                        "title": "#7 :bust_in_silhouette: 사용자명이나 프로필 사진, 사용자 지정 상태, 게임 활동에 저희의 규칙을 위반하는 내용이 있어서는 안됩니다.",
                        "description": "- 여기에는 저희의 직원을 사용자명이나 프로필 사진 등으로 사칭하는 것도 포함됩니다.",
                        "color": 16711680
                    },
                    {
                        "title": "#8 :telephone: Unsolicited advertising (through voice, text channels, or DMs) is prohibited.",
                        "color": 16775159
                    },
                    {
                        "title": "#8 :telephone: (음성, 텍스트 채널, 개인 메세지 등으로) 저희가 청하지 않은 내용의 광고들은 금지됩니다.",
                        "color": 16711680
                    },
                    {
                        "title": "#9 :speaking_head: Accusing someone for breaking rules in public chats is prohibited.",
                        "description": "- Instances of such are considered defamatory. If you have any proof, contact a Staff member privately about it and we will handle the situation accordingly.",
                        "color": 16775159
                    },
                    {
                        "title": "#9 :speaking_head: 누군가가 규칙을 어겼다고 공개 채팅방에서 고발하는 행위는 금지되어있습니다.",
                        "description": "- 명예훼손으로 간주되므로, 만약 누군가가 규칙을 어긴 증거가 있으시다면 저희 직원 분들중 한 분에게 개인 메세지로 신고해주세요.",
                        "color": 16711680
                    },
                    {
                        "title": "#10 :face_with_symbols_over_mouth: General toxic behaviour is not allowed in any channels.",
                        "description": "- This includes, but is not limited to, earrape, loud/annoying noises and screams in voice chats and posted audio/video files, spreading slander/lies, and rude, insulting or derogatory language towards users/staff.",
                        "color": 16775159
                    },
                    {
                        "title": "#10 :face_with_symbols_over_mouth: 무례하게 행동하는 행위는 그 어떠한 채널에서도 허용되지 않습니다.",
                        "description": "- 여기에는 고막 테러, 짜증나는 소음 및 비명, 허위 사실 유포, 그리고 타인을 향한 모욕 및 욕설도 포함됩니다.",
                        "color": 16711680
                    }
                ],
                "username": "Captain Hook",
                "avatar_url": "https://cdn.discordapp.com/embed/avatars/0.png"
            }
        }
    ]
}
```

**Comment by vivisrc** [comment]
Provided URL doesn't contain URL-safe base 64, which isn't supported.

**Comment by XboxBedrock** [comment]
Oh well that fixed it, thanks then XD
